apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nodejs-app-rollout
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nodejs-app
  strategy:
    canary:
      steps:
      - setWeight: 20
        pause:
          duration: 30s
      - setWeight: 40
        pause:
          duration: 30s
      - setWeight: 60
        pause:
          duration: 30s
      - setWeight: 80
        pause:
          duration: 30s
      - setWeight: 100
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: your-dockerhub-username/nodejs-app:latest
        ports:
        - containerPort: 8000
